//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeMvcApi
{
    using System;
    using System.Collections.Generic;

          [Serializable()]

    public partial class Clark
    {
        public Clark()
        {
            this.Managements = new HashSet<Management>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Salary { get; set; }
        public string Position { get; set; }
        public Nullable<int> TotalSalary { get; set; }
    
        public virtual ICollection<Management> Managements { get; set; }
    }
}
