//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OfficeMvcApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OfficeDbEntities : DbContext
    {
        public OfficeDbEntities()
            : base("name=OfficeDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Additional> Additionals { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<Clark> Clarks { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Management> Managements { get; set; }
    }
}
